if which rbenv > /dev/null; then
  eval "$(rbenv init -)";
fi

# ---- Command Completion ----
# ----------------------------
autoload -U compinit; compinit
# Show completion on first TAB
setopt menucomplete

# ---- History ----
# -----------------
setopt HIST_IGNORE_ALL_DUPS # Removes duplicate lines from history

autoload -U colors; colors
PROMPT="%{${fg[red]}%}%~
%{${fg[green]}%}$ %{${fg[default]}%}"

RPROMPT="%{${fg[blue]}%}%w @ %D{%L:%M:%S}%{${fg[default]}%}"
